/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmerbuddy;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author VIRAJ
 */
public class Fertilizers extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    String uname,email,contactno,message;
          int id=0;
    public Fertilizers() {
        initComponents();
        displayInfoFirst();
    }
    public void displayInfoFirst(){
        infoOf.setVisible(true);
        homemade.setVisible(false);
        contact.setVisible(false);
        contact1.setVisible(false);
    }
    
    public int getId(){
        ResultSet rs=null;
        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
              Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/test","root","root");
              String sql="select max(id) from Contact";
              Statement st=con.createStatement();
              rs = st.executeQuery(sql);
              while(rs.next()){
                  id=rs.getInt(1);
                  id++;
              }
        }catch(Exception e){
            e.printStackTrace();
        }
        return id;
    }
    void insertDetails()
      {
          try{
              Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
              Connection con=DriverManager.getConnection("jdbc:derby://localhost:1527/test","root","root");
              String sql="Insert into Contact values(?,?,?,?,?)";
              PreparedStatement stmt=con.prepareStatement(sql);
              stmt.setInt(1,getId());
              stmt.setString(2, uname);
              stmt.setString(3, email);
              stmt.setString(4, contactno);
              stmt.setString(5, message);
              int i=stmt.executeUpdate();
              if(i>0){
                  JOptionPane.showMessageDialog(this,"Message has been send,Thank you!!");
              }
              
              else{
                  JOptionPane.showMessageDialog(this,"Message has not send,Try again!");
              }
          }catch(Exception e){
              e.printStackTrace();
          }
      }
    
    boolean validation(){
          
          uname=txt_uname1.getText();
          email=txt_email1.getText();
          contactno=txt_contact1.getText();
          message=txt_message1.getText();
          
          if(uname.equals("")){
              JOptionPane.showMessageDialog(this,"Please enter your username");
             return false; 
          }
          if(email.equals("")){
              JOptionPane.showMessageDialog(this,"Please enter your Email");
              return false;
          }
          if(contactno.equals("")){
              JOptionPane.showMessageDialog(this,"Please enter Your Contactno");
              return false;
          }
          if(message.equals("")){
              JOptionPane.showMessageDialog(this, "Please enter Your message");
              return false;
          }
          return true;
    }
      public void checkContactno(){
          contactno=txt_contact1.getText();
          if(contactno.length()==10){
              lbl_contact_error1.setText(" ");
          }else{
              lbl_contact_error1.setText("Contact should be 10 digits");
          }
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combobox = new javax.swing.JComboBox<>();
        ofi = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        myof = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        slof = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        contact1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_message1 = new javax.swing.JTextArea();
        txt_contact1 = new javax.swing.JTextField();
        txt_uname1 = new javax.swing.JTextField();
        txt_email1 = new javax.swing.JTextField();
        send1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbl_contact_error1 = new javax.swing.JLabel();
        lbl_pass_error = new javax.swing.JLabel();
        contact = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbl_contact_error = new javax.swing.JLabel();
        comboboxquestion = new javax.swing.JComboBox<>();
        ans5 = new javax.swing.JLabel();
        ans1 = new javax.swing.JLabel();
        ans2 = new javax.swing.JLabel();
        ans3 = new javax.swing.JLabel();
        ans4 = new javax.swing.JLabel();
        homemadeof = new javax.swing.JPanel();
        homemade = new javax.swing.JLabel();
        infoOf = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        Home_of = new javax.swing.JLabel();

        combobox.setBackground(new java.awt.Color(0, 51, 0));
        combobox.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        combobox.setForeground(new java.awt.Color(51, 102, 0));
        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Information", "Crops", "Vegetables", "Fruits", " " }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ofi.setBackground(new java.awt.Color(51, 102, 0));
        ofi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        ofi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ofiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ofiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ofiMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Organic Fertilizers Information");
        ofi.add(jLabel3);

        getContentPane().add(ofi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 320, 40));

        myof.setBackground(new java.awt.Color(51, 102, 0));
        myof.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        myof.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myofMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myofMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myofMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Make Your Own Organic Fertilizers");
        myof.add(jLabel2);

        getContentPane().add(myof, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 370, 40));

        slof.setBackground(new java.awt.Color(51, 102, 0));
        slof.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        slof.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slofMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                slofMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                slofMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Shopping Links for Organic Fertilizers");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        slof.add(jLabel7);

        getContentPane().add(slof, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 120, -1, -1));

        contact1.setBackground(new java.awt.Color(0, 51, 0));
        contact1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("<html>You can also contact us on email : </html>");
        contact1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 350, 40));

        jLabel12.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ask How we can help You:");
        contact1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 390, 40));

        jLabel13.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Username       :");
        contact1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel14.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Email             :");
        contact1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Contact No     :");
        contact1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        txt_message1.setColumns(20);
        txt_message1.setRows(5);
        jScrollPane2.setViewportView(txt_message1);

        contact1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 550, -1));

        txt_contact1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_contact1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt_contact1MouseReleased(evt);
            }
        });
        txt_contact1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_contact1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_contact1KeyReleased(evt);
            }
        });
        contact1.add(txt_contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 380, 40));
        contact1.add(txt_uname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 380, 40));
        contact1.add(txt_email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 380, 40));

        send1.setBackground(new java.awt.Color(51, 153, 0));
        send1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        send1.setForeground(new java.awt.Color(0, 51, 0));
        send1.setText("SEND");
        send1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send1ActionPerformed(evt);
            }
        });
        contact1.add(send1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 80, -1));

        jLabel16.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 255));
        jLabel16.setText("<html><u>121nupur4055@sjcem.edu.in</u></html>");
        contact1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 240, -1));

        jLabel17.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Message:");
        contact1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel18.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 255));
        jLabel18.setText("<html><u>+91 18294 4853</u></html>");
        contact1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 240, -1));

        jLabel19.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 255));
        jLabel19.setText("<html><u>121vaibhavi4018@sjcem.edu.in</u></html>");
        contact1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 240, -1));

        lbl_contact_error1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        lbl_contact_error1.setForeground(new java.awt.Color(255, 51, 0));
        contact1.add(lbl_contact_error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 300, 40));

        lbl_pass_error.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 12)); // NOI18N
        lbl_pass_error.setForeground(new java.awt.Color(255, 0, 0));
        contact1.add(lbl_pass_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 300, 40));

        getContentPane().add(contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 930, 570));

        contact.setBackground(new java.awt.Color(0, 51, 0));
        contact.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Frequently Asked Questions:");
        contact.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 390, 40));

        lbl_contact_error.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        lbl_contact_error.setForeground(new java.awt.Color(255, 51, 0));
        contact.add(lbl_contact_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 300, 40));

        comboboxquestion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        comboboxquestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Q. Which fertilizers would be useful for black soil?", "Q. Which fertilizers is used for abundant yield of tomato crops?", "Q. What are the climatic conditions for better growth of rubber?", "Q. Which crops are grown in black soil?", "Q. Which crops gives better yield in red soil?" }));
        comboboxquestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxquestionActionPerformed(evt);
            }
        });
        contact.add(comboboxquestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 680, 30));

        ans5.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        ans5.setForeground(new java.awt.Color(255, 255, 255));
        ans5.setText("<html>Cotton, Wheat, Rice, Pulses, Tobacco, Oil seeds, Potatoes and Fruits gives better yeild on red Soil.</html>");
        contact.add(ans5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 550, 50));

        ans1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        ans1.setForeground(new java.awt.Color(255, 255, 255));
        ans1.setText("<html>Urvi 100% Natural Organic Black soil with magic powder, cocpeat & vermicomposet Fertilizer(975 g, Powder) </html>");
        contact.add(ans1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 570, -1));

        ans2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        ans2.setForeground(new java.awt.Color(255, 255, 255));
        ans2.setText("<html>BPR and NPK Fertilizers significantly influenced the growth and yeild of the tomato compared to control Treatement.</html>");
        contact.add(ans2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 550, 50));

        ans3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        ans3.setForeground(new java.awt.Color(255, 255, 255));
        ans3.setText("<html>Rubber Trees require moist and humid climate with heavy rain falls of more than 200cm.</html>");
        contact.add(ans3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 550, 50));

        ans4.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        ans4.setForeground(new java.awt.Color(255, 255, 255));
        ans4.setText("<html>Wheat, Groundnut and cotton are few of the crops which require black soil for their growth.</html>");
        contact.add(ans4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 550, 50));

        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 930, 500));

        homemadeof.setBackground(new java.awt.Color(0, 51, 0));
        homemadeof.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homemade.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        homemade.setForeground(new java.awt.Color(255, 255, 255));
        homemade.setText("<html><h1><u> Make Your Own Organic Fertilizers </u></h1><br><b>1)Vineger as Fertilizers:</b><br> Always dilute 1 cup of vineger in 2 gallons of fresh water while watering your plants. This is one of the best  DIY Fertilizers for your plants. Just like coffee, the acid-loving plants enjoy tea as  a fetilizer. Because tea contains citric and tannic acid which helps maintain the pH levels of the soil.<br> <br> 2) <b>Epsom salt Fetilizers:</b><br> Dissolve 1 tablespoon of Epsom salt in 1 gallon of water. Shake the solution thoroughly.  Use the solution to water your plants. Water them with this solution once per month during the growing season.<br> <br> 3)<b>Eggshell as fertilizers:</b><br> Save your eggs shells and allow them to air dry. Place the dried shells in a  blender and pulse until they're powdery-fine. Sprinkle the shell powder around the plants.<br> <br> 4)<b>Repupose your banana peels:</b><br> We eat bananas for their potassium and roses love potassium too. Simply bury peels in a hole along side the rose bush so they can compost naturally. As the rose grows burry the peels into the soil's top layer. Both of these approaches will provide much needed potassium for the plant's proper growth<br> <br> 5)<b>Make Your own Compost:<b><br> Save your fruit and vegetable scraps, newspapers, grass clippings, and other compostable  materials. Use them to start a compost bin or pile. Add a bit of water from time to time, and turn your pile to speed up the composting process. When everything has broken down into a dark, rich soil, it's time to spread it in your garden.  </html>");
        homemadeof.add(homemade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1010, 600));

        infoOf.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        infoOf.setForeground(new java.awt.Color(255, 255, 255));
        infoOf.setText("<html><h1><u> Information about Organic Fertilizers </u></h1>Organic Fertilizers are fertilizers that are naturally produced. Fertilizers are materials that can be added to soil or plants, In order to provide nutrients and sustain growth. \nTypical organic fertilizers include all animal waste including meat  processing waste, manure, slurry, and guano; Plus plant based fertilizer such as compost, and bio-solids. Inorganic\n \"Organic Fertilizers\" include minerals and ash. The Organic-ness refers to the priciples of organic agriculture, which  determines weather a fertilizers can be used for commercial organic Agriculture, not weather \nthe Fertilizer consist of Organic Compounds. The main Organic Fertilizers are peats, animal wastes, Plant wastes from Agriculture and treated  sewage sludge.<br>\n<br>\nYou can also get an information about how to make organic fetilizers at home..click on above button.</html>\n");
        homemadeof.add(infoOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1010, 250));

        getContentPane().add(homemadeof, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 1050, 620));

        jButton6.setBackground(new java.awt.Color(0, 51, 0));
        jButton6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Home");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 170, 50));

        jButton4.setBackground(new java.awt.Color(0, 51, 0));
        jButton4.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Fertillizers");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 170, 50));

        jButton3.setBackground(new java.awt.Color(0, 51, 0));
        jButton3.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Q&A");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 170, 50));

        jButton5.setBackground(new java.awt.Color(0, 51, 0));
        jButton5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Contact Us");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, 170, 50));

        jButton1.setBackground(new java.awt.Color(0, 51, 0));
        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LogOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 50, 170, 50));

        jComboBox1.setBackground(new java.awt.Color(0, 51, 0));
        jComboBox1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 102, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Information", "crops", "Vegetables", "Fruit" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 160, 50));

        Home_of.setBackground(new java.awt.Color(0, 51, 0));
        Home_of.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        Home_of.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmerbuddy/iamges/home.jpg"))); // NOI18N
        getContentPane().add(Home_of, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 860));

        setSize(new java.awt.Dimension(1535, 903));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        if(combobox.getSelectedIndex()==1){
            Crops Crops=new Crops();
            Crops.show();
            this.dispose();
        }
        if(combobox.getSelectedIndex()==2){
            Vegetable Veg=new Vegetable();
            Veg.show();
            this.dispose();
        }
        if(combobox.getSelectedIndex()==3){
            Fruit Fruit=new Fruit();
            Fruit.show();
            this.dispose();
        }

    }//GEN-LAST:event_comboboxActionPerformed

    private void myofMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myofMouseEntered
        Color clr=new Color(0,51,0);
        myof.setBackground(clr);
    }//GEN-LAST:event_myofMouseEntered

    private void myofMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myofMouseExited
        Color clr=new Color(51,102,0);
        myof.setBackground(clr);
    }//GEN-LAST:event_myofMouseExited

    private void ofiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ofiMouseEntered
        Color clr=new Color(0,51,0);
        ofi.setBackground(clr);
    }//GEN-LAST:event_ofiMouseEntered

    private void ofiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ofiMouseExited
        Color clr=new Color(51,102,0);
        ofi.setBackground(clr);
    }//GEN-LAST:event_ofiMouseExited

    private void slofMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slofMouseEntered
        Color clr=new Color(0,51,0);
        slof.setBackground(clr);
    }//GEN-LAST:event_slofMouseEntered

    private void slofMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slofMouseExited
         Color clr=new Color(51,102,0);
        slof.setBackground(clr);
    }//GEN-LAST:event_slofMouseExited

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Home Home=new Home();
        Home.show();
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       contact1.setVisible(false);
        contact.setVisible(false);
         ans1.setVisible(false);
            ans2.setVisible(false);
            ans3.setVisible(false);
            ans4.setVisible(false);
            ans5.setVisible(false);
            ofi.setVisible(true);
            myof.setVisible(true);
            slof.setVisible(true);
            homemadeof.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        contact1.setVisible(false);
        contact.setVisible(true);
         ans1.setVisible(false);
            ans2.setVisible(false);
            ans3.setVisible(false);
            ans4.setVisible(false);
            ans5.setVisible(false);
            ofi.setVisible(false);
            myof.setVisible(false);
            slof.setVisible(false);
            homemadeof.setVisible(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        contact1.setVisible(true);
        contact.setVisible(false);
         ans1.setVisible(false);
            ans2.setVisible(false);
            ans3.setVisible(false);
            ans4.setVisible(false);
            ans5.setVisible(false);
            ofi.setVisible(false);
            myof.setVisible(false);
            slof.setVisible(false);
            homemadeof.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login login=new login();
        login.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void myofMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myofMouseClicked

        homemade.setVisible(true);
        infoOf.setVisible(false);
    }//GEN-LAST:event_myofMouseClicked

    private void ofiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ofiMouseClicked
        infoOf.setVisible(true);
        homemade.setVisible(false);
    }//GEN-LAST:event_ofiMouseClicked

    private void slofMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slofMouseClicked
       shop shop=new shop();
       shop.show();
       this.dispose();
    }//GEN-LAST:event_slofMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        shop shoplink=new shop();
        shoplink.show();
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex()==1){
            Crops Crops=new Crops();
            Crops.show();
            this.dispose();
        }
        if(jComboBox1.getSelectedIndex()==2){
            Vegetable Veg=new Vegetable();
            Veg.show();
            this.dispose();
        }
        if(jComboBox1.getSelectedIndex()==3){
            Fruit Fruit=new Fruit();
            Fruit.show();
            this.dispose();
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void comboboxquestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxquestionActionPerformed
        // TODO add your handling code here:
        if(comboboxquestion.getSelectedIndex()==1){
            ans1.setVisible(true);
            ans2.setVisible(false);
            ans3.setVisible(false);
            ans4.setVisible(false);
            ans5.setVisible(false);
        }
        if(comboboxquestion.getSelectedIndex()==2){
            ans1.setVisible(false);
            ans2.setVisible(true);
            ans3.setVisible(false);
            ans4.setVisible(false);
            ans5.setVisible(false);
        }
        if(comboboxquestion.getSelectedIndex()==3){
            ans1.setVisible(false);
            ans2.setVisible(true);
            ans3.setVisible(false);
            ans4.setVisible(false);
            ans5.setVisible(false);
        }
    }//GEN-LAST:event_comboboxquestionActionPerformed

    private void txt_contact1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_contact1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contact1MousePressed

    private void txt_contact1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_contact1MouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_contact1MouseReleased

    private void txt_contact1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contact1KeyPressed

    }//GEN-LAST:event_txt_contact1KeyPressed

    private void txt_contact1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contact1KeyReleased
        checkContactno();
    }//GEN-LAST:event_txt_contact1KeyReleased

    private void send1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send1ActionPerformed
        // TODO add your handling code here:
        if(validation()) {
            insertDetails();
        }
    }//GEN-LAST:event_send1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fertilizers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fertilizers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fertilizers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fertilizers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fertilizers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Home_of;
    private javax.swing.JLabel ans1;
    private javax.swing.JLabel ans2;
    private javax.swing.JLabel ans3;
    private javax.swing.JLabel ans4;
    private javax.swing.JLabel ans5;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JComboBox<String> comboboxquestion;
    private javax.swing.JPanel contact;
    private javax.swing.JPanel contact1;
    private javax.swing.JLabel homemade;
    private javax.swing.JPanel homemadeof;
    private javax.swing.JLabel infoOf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_contact_error;
    private javax.swing.JLabel lbl_contact_error1;
    private javax.swing.JLabel lbl_pass_error;
    private javax.swing.JPanel myof;
    private javax.swing.JPanel ofi;
    private javax.swing.JButton send1;
    private javax.swing.JPanel slof;
    private javax.swing.JTextField txt_contact1;
    private javax.swing.JTextField txt_email1;
    private javax.swing.JTextArea txt_message1;
    private javax.swing.JTextField txt_uname1;
    // End of variables declaration//GEN-END:variables
}
